install:
  - C:\Python36\python.exe -m pip install mypy
  - C:\Python36\python.exe -m pip install -e .[d]

# Not a C# project
build: off

test_script:
  - C:\Python36\python.exe tests/test_black.py
  - C:\Python36\python.exe -m mypy black.py blackd.py tests/test_black.py blib2to3

after_test:
  - C:\Python36\python.exe -m pip install pyinstaller
  - "%CMD_IN_ENV% C:\\Python36\\python.exe -m PyInstaller --clean -F --add-data
    blib2to3/;blib2to3 black.py"

artifacts:
  - path: dist/black.exe

deploy:
  provider: GitHub
  description: ""
  auth_token:
    secure: uplI9CJ2dTGcEBCbZuIn+Qb4rC38hOoRSH9lcwuGCr5g9fSnhK1MZdNT6Cjf/mFL
  on:
    APPVEYOR_REPO_TAG: true
