language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
env:
  - TEST_CMD="coverage run -m unittest"
install:
  - pip install coverage coveralls pre-commit
  - pip install -e '.[d]'
script:
  - $TEST_CMD
after_success:
  - coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "lint"
      python: 3.7
      env:
        - TEST_CMD="pre-commit run --all-files --show-diff-on-failure"
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
    - name: "3.9"
      python: 3.9-dev
  allow_failures:
    - python: 3.9-dev
before_deploy:
  - pip install pyinstaller
  - pyinstaller --clean -F --add-data src/blib2to3/:blib2to3 src/black/__init__.py
deploy:
  provider: releases
  api_key:
    secure: chYvcmnRqRKtfBcAZRj62rEv0ziWuHMl6MnfQbd1MOVQ4njntI8+CCPk118dW6MWSfwTqyMFy+t9gAgQYhjkLEHMS2aK9Z2wCWki1MkBrkMw5tYoLFvPu0KQ9rIVihxsr93a/am6Oh/Hp+1uuc4zWPUf1ubX+QlCzsxjCzVso1kTJjjdN04UxvkcFR+sY2d9Qyy9WcdifChnLwdmIJKIoVOE7Imm820nzImJHkJh8iSnjBjL98gvPPeC/nWTltsbErvf2mCv4NIjzjQZvHa87c7rSJGbliNrAxCSyyvBX+JNeS8U2fGLE83do0HieyjdPbTuc27e2nsrrihgPh+hXbiJerljclfp5hsJ5qGz5sS9MU1fR7sSLiQQ2v0TYB5RRwd34TgGiLwFAZZmgZOfMUCtefCKvP8qvELMSNd99+msfPEHiuhADF0bKPTbCUa6BgUHNr6woOLmHerjPHd6NI/a8Skz/uQB4xr3spLSmfUmX0fEqyYUDphkGPNH8IsvC1/F2isecW9kOzEWmB5oCmpMTGm4TIf3C01Nx+9PVwB2Z+30hhbfIEBxD4loRFmh/hU5TIQEpneF8yoIfe9EnMaoZbq86xhADZXvLIZvpXUdm1NQZDG6na2S1fwyOUKQsW6BWLcfoZZwZlrXrViD1jBsHBV++s+lxShTeTCszlo=
  file:
    - dist/black
  skip_cleanup: true
  on:
    condition: $TRAVIS_PYTHON_VERSION == '3.6'
    repo: psf/black
    tags: true
