name: black_docs
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - Sphinx==1.7.2
  - pip:
      - recommonmark==0.4.0
      - git+https://git@github.com/psf/black.git
      - setuptools_scm==3.3.3
