name: Upload self-contained binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [windows-2019, ubuntu-20.04, macos-11.0]
        include:
          - os: windows-2019
            pathsep: ";"
            executable_suffix: ".exe"
            executable_mime: "application/vnd.microsoft.portable-executable"
          - os: ubuntu-20.04
            pathsep: ":"
            executable_suffix: ".elf"
            executable_mime: "application/x-executable"
          - os: macos-11.0
            pathsep: ":"
            executable_suffix: ""
            executable_mime: "application/x-mach-binary"
            env:
              CFLAGS: "-arch arm64 -arch x86_64"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: matrix.os != 'macos-11.0'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build binary
        if: matrix.os != 'macos-11.0'
        run: |
          python -m PyInstaller -F --name black${{ matrix.executable_suffix }} --add-data 'src/blib2to3${{ matrix.pathsep }}blib2to3' src/black/__main__.py

      - name: Install dependencies macOS
        if: matrix.os == 'macos-11.0'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          git clone https://github.com/rokm/pyinstaller -b macos11-arm-support
          cd pyinstaller/bootloader
          mkdir -p build
          clang -arch x86_64 -mmacos-version-min=10.7  `ls src/*.c` -o build/run-x86_64 -lm -lz
          clang -isysroot /Applications/Xcode2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.*.sdk -arch arm64 -mmacos-version-min=11.0 -o build/run-arm64 `ls src/*.c` -lz -lc
          lipo -create -o ../PyInstaller/bootloader/Darwin-64bit/run build/run-arm64 build/run-x86_64
          lipo -archs ../PyInstaller/bootloader/Darwin-64bit/run
          cd ../..
          python setup.py install

      - name: Build binary macOS
        if: matrix.os == 'macos-11.0'
        run: |
          CFLAGS="-arch arm64 -arch x86_64" python -m PyInstaller -F --name black${{ matrix.executable_suffix }} --add-data 'src/blib2to3${{ matrix.pathsep }}blib2to3' src/black/__main__.py

      - name: Upload binary as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/black${{ matrix.executable_suffix }}
          asset_name: black${{ matrix.executable_suffix }}
          asset_content_type: ${{ matrix.executable_mime }}
